### ISSUE TITLE
Compile error on ubuntu 16.04.4 LTS / macOS while using function : WEXITSTATUS

### ISSUE THREAD

**Issue by fstqwq** [CDFLS/Judge#1]
MultiCompiler.h: In function ‘void InitCompiler()’:
MultiCompiler.h:22:7: error: lvalue required as unary ‘&’ operand
   if (WEXITSTATUS(system((Compiler[i].dependency+" >/dev/null 2>/dev/null").c_str()))==0)
       ^
MultiCompiler.h: In function ‘int Compile(std::__cxx11::string, std::__cxx11::string, int)’:
MultiCompiler.h:47:9: error: lvalue required as unary ‘&’ operand
  return WEXITSTATUS(system(str));
         ^
judge.cpp: In member function ‘JudgeResult TestPoint::JudgePoint(std::__cxx11::string, double, int, int, std::__cxx11::string&)’:
judge.cpp:407:6: error: lvalue required as unary ‘&’ operand
  if (WEXITSTATUS(system(str))!=0)
      ^
......

反正直接删了这个函数就能够过编译……
ubuntu下g++版本为
fstqwq@fstqwq:\~/code/cpp/Judge/example$ g++ --version
g++ (Ubuntu 5.4.0-6ubuntu1~16.04.4) 5.4.0 20160609
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

macOS不清楚……
反正CE是一样的

**Comment by Heptagon196** [comment]
改了一下， 应该可以了（不过我这里无法重现）。明天在学校主机上试一下。
现在使用clang也可以通过编译。我的版本是3.9.1。

-----------------------------------------------------------------------
CentOS上gcc 4.9.0通过编译。
